board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.BoardList.as_view(), name='board_list'),
    path('write/', views.BoardCreate.as_view(), name='board_write'),
    path('<int:pk>/', views.BoardDetail.as_view(), name='board_detail'),
    path('<int:pk>/update/', views.BoardUpdate.as_view(), name='board_update'),
    path('<int:pk>/delete/', views.BoardDelete.as_view(), name='board_delete'),
    path('setFixPost/', views.BoardTopFix.as_view(), name='board_topFix'),
    path('notice/', views.NoticeList.as_view(), name='notice_list'),
    path('notice/<int:pk>/', views.NoticeDetail.as_view(), name='notice_detail'),
    path('notice/write/', views.NoticeCreate.as_view(), name='notice_write'),
    path('notice/<int:pk>/update/', views.NoticeUpdate.as_view(), name='notice_update'),
    path('notice/<int:pk>/delete/', views.NoticeDelete.as_view(), name='notice_delete'),
    path('notice/setFixNotice/', views.NoticeTopFix.as_view(), name='notice_topFix'),
]

django_board_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('board.urls')),
    path('board/', include('board.urls')),
    path('notice/', include('board.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
import os


# 사보 게시판
class Post(models.Model):
    # 게시글 제목
    title = models.CharField(max_length=50, verbose_name='제목')
    # 고정글
    pin = models.BooleanField(verbose_name='고정글 설정', default=False)
    # 글 내용
    content = RichTextField(blank=True, null=True, verbose_name='내용')
    # 작성일(작성된 날짜 자동 등록)
    created_at = models.DateTimeField(auto_now_add=True)
    # 수정 시 수정된 날짜 새로 생성
    updated_at = models.DateTimeField(auto_now=True)
    # 파일 업로드
    file_upload = models.FileField(upload_to='board/files/%Y/%m/%d/', blank=True, verbose_name='파일')
    # 작성자
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='작성자')

    def __str__(self):
        return f'[{self.pin}] [{self.pk}] {self.title} __ {self.author}'

    def get_absolute_url(self):
        return f'/board/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


# 카테고리
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


# 공지사항
class Notice(models.Model):
    # 제목
    title = models.CharField(max_length=50, verbose_name='제목')
    # 고정글
    pin = models.BooleanField(verbose_name='중요글 설정', default=False)
    # 카테고리
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, verbose_name='카테고리')
    # 글 내용
    content = RichTextField(blank=True, null=True, verbose_name='내용')
    # 작성일
    created_at = models.DateTimeField(auto_now_add=True)
    # 수정시 수정된 날짜 업데이트
    updated_at = models.DateTimeField(auto_now=True)
    # 파일 업로드
    file_upload = models.FileField(upload_to='board/files/%Y/%m/%d/', blank=True, verbose_name='첨부파일')
    # 작성자
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}] [{self.pin}] [{self.category.name}] {self.title} __ {self.author}'

    def get_absolute_url(self):
        return f'/notice/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

board/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post, Notice


class BoardList(ListView):
    model = Post
    paginate_by = 15
    template_name = 'board/board_list.html'
    context_object_name = 'board_list'
    ordering = '-pk'

    def get_context_data(self, **kwargs):
        context = super(BoardList, self).get_context_data(**kwargs)
        # 상단고정
        post_fixed = Post.objects.filter(pin=True).order_by('-pk')
        context['post_fixed'] = post_fixed

        return context


class BoardDetail(DetailView):
    model = Post
    template_name = 'board/board_detail.html'


class BoardCreate(CreateView):
    model = Post
    template_name = 'board/board_write.html'
    fields = ['title', 'file_upload', 'pin', 'content']


class BoardUpdate(UpdateView):
    model = Post
    template_name = 'board/board_write.html'
    fields = ['title', 'file_upload', 'pin', 'content']


class BoardDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('board:board_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


# 고정글 설정 페이지
class BoardTopFix(ListView, UpdateView):
    model = Post
    paginate_by = 5
    template_name = 'board/board_top_fix.html'
    ordering = '-pk'
    fields = ['pin', 'pk', 'title', 'created_at']

    def get_context_data(self, **kwargs):
        context = super(BoardTopFix, self).get_context_data(**kwargs)
        # 상단고정
        post_fixed = Post.objects.filter(pin=True).order_by('-pk')
        context['post_fixed'] = post_fixed

        return context


class NoticeList(ListView):
    model = Notice
    template_name = 'board/notice_list.html'
    context_object_name = 'notice_list'
    ordering = '-pk'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NoticeList, self).get_context_data(**kwargs)
        # 상단 고정
        notice_fixed = Notice.objects.filter(pin=True).order_by('-pk')
        context['notice_fixed'] = notice_fixed
        return context


class NoticeDetail(DetailView):
    model = Notice


class NoticeCreate(CreateView):
    model = Notice
    template_name = 'board/notice_write.html'
    fields = ['category', 'title', 'file_upload', 'pin', 'content']


class NoticeUpdate(UpdateView):
    model = Notice
    template_name = 'board/notice_write.html'
    fields = ['category', 'title', 'file_upload', 'pin', 'content']


class NoticeDelete(DeleteView):
    model = Notice
    success_url = reverse_lazy('board:notice_list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class NoticeTopFix(ListView):
    model = Notice
    paginate_by = 5
    template_name = 'board/notice_top_fix.html'
    ordering = '-pk'
    fields = ['pin', 'pk', 'category', 'title', 'created_at']

    def get_context_data(self, **kwargs):
        context = super(NoticeTopFix, self).get_context_data(**kwargs)
        # 상단고정
        notice_fixed = Notice.objects.filter(pin=True).order_by('-pk')
        context['notice_fixed'] = notice_fixed

        return context

board/templates/board/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/f9138e08ba.js" crossorigin="anonymous"></script>
    <script src={% static 'board/javascript/bootstrap.min.js' %} type="text/javascript"></script>
    <link rel="stylesheet" href={% static 'board/bootstrap/bootstrap.css' %} type="text/css">
    <link rel="stylesheet" href={% static 'board/bootstrap/board_list_style.css' %} type="text/css">
    <title>밀리의 서재-기업 도서관</title>
</head>

<body style="margin: 5%">
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8" style="text-align: center;"><a href="/"><img src={% static 'board/image/header_logo.png' %} alt="Aixcon" width="100px;"></a></div>
        <div class="col-lg-2" style="text-align: end;">
            <div class="dropdown">
                <div class="btn-group">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="background-color: transparent;">
                        Aixcon
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="">로그아웃</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% block nav_bar %}

{% endblock %}

{% block sabo_tab %}

{% endblock %}

{% block notice_tab %}

{% endblock %}



</body>
</html>

board/templates/board/board_list.html
{% extends 'board/base.html' %}
{% load static %}
{% block nav_bar %}
<div class="container">
    <div class="row">
        <div class="col-lg">
            <a href="{% url 'board:board_list' %}"><button class="btn btn-outline-warning">사보 게시판</button></a>
            <a href="{% url 'board:notice_list' %}"><button class="btn btn-outline-warning">공지사항</button></a>
        </div>
        <div class="co-ml-auto">
            <a href="{% url 'board:board_topFix' %}"><button class="btn btn-secondary">고정글 설정</button></a>
            <a href="{% url 'board:board_write' %}"><button class="btn btn-secondary">글쓰기</button></a>
        </div>
    </div>
</div>
<br/>
{% endblock %}
{% block sabo_tab %}
    <table class="table table-hover col-lg-auto" style="text-align: center;">
        <thead>
        <tr>
            <th class="col-lg-1" scope="col">번호</th>
            <th class="col-lg-7" scope="col">제목</th>
            <th class="col-lg-2" scope="col">등록일</th>
            <th class="col-lg-2" scope="col">Handle</th>
        </tr>
        {% if p %}
        {% else %}
            {% if post_fixed %}
                {% for pin in post_fixed %}
                    <tr class="table-warning table-hover">
                        <td><i class="fas fa-bullhorn"></i></td>
                        <td><a href="{{ pin.get_absolute_url }}">{{ pin.title }}</a></td>
                        <td>{{ pin.created_at|date:'Y-m-d' }}</td>
                        <td></td>
                    </tr>
                {% endfor%}
            {% endif %}
        {% endif %}
        </thead>
        <tbody>
        {# 게시글 #}
        {% for p in board_list %}
            <tr>
                <th scope="row">{{ p.pk }}</th>
                <td><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></td>
                <td>{{ p.created_at|date:'Y-m-d' }}</td>
                <td>
                    <div class="d-grid gap-2 d-md-block">
                        <a href="/board/{{ p.pk }}/update"><button class="btn btn-secondary" type="button">수정</button></a>
                        <a href="/board/{{ p.pk }}/delete" onclick="return confirm('정말 {{ p.title }}을(를) 삭제 하시겠습니까?');">
                            <button class="btn btn-danger" type="button">삭제</button>
                        </a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {#    페이지 네이션#}
    {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for page in page_range %}
                    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}

board/templates/board/board_top_fix.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h4>고정글 설정</h4>
<table>
    <thead>
    <tr>
        <th>체크박스</th>
        <th>제목</th>
        <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        {% if p %}
        {% else %}
            {% if post_fixed %}
                {% for pin in post_fixed %}
                    <tr class="table-warning table-hover">
                        <td><i class="fas fa-bullhorn"></i></td>
                        <td>{{ pin.title }}</td>
                        <td>{{ pin.created_at|date:'Y-m-d' }}</td>
                        <td></td>
                    </tr>
                {% endfor%}
            {% endif %}
        {% endif %}
    </tr>
    </tbody>
</table>
<div>
    <button>Up</button>
    <button>Down</button>
    <button>설정 저장</button>
</div>
<button>고정글 해제</button>
<table>
    <thead>
    <tr>
        <th>체크박스</th>
        <th>번호</th>
        <th>제목</th>
        <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    {% for p in post_list %}
        <tr>
            <td>o</td>
            <td>{{ p.pk }}</td>
            <td>{{ p.title }}</td>
            <td>{{ p.created_at|date:'Y-m-d' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div>
    << pagination >>
</div>
<div>
    <button>고정글 저장</button>
</div>
<div>
    <button>닫기</button>
</div>
</body>
</html>

board/templates/board/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
</head>
<body>
    <h1>사보 게시판</h1>

    {% for p in posts %}
        <hr/>
        <h3><a href="{{ p.get_absolute_url }}"> {{ p.title }} </a></h3>
        <h4> {{ p.created_at }} </h4>
        <p> {{ p.content }} </p>
    {% endfor %}
</body>
</html>

board/templates/board/notice_list.html
{% extends 'board/base.html' %}
{% block nav_bar %}
    <div class="container">
        <div class="row border-bottom">
            <div class="col-auto">
                <a href="{% url 'board:board_list' %}"><button class="btn btn-outline-warning">사보 게시판</button></a>
                <a href="{% url 'board:notice_list' %}"><button class="btn btn-outline-warning">공지사항</button></a>
            </div>
            <div class="ml-auto">
                <a href="{% url 'board:notice_topFix' %}"><button class="btn btn-secondary">고정글 설정</button></a>
                <a href="{% url 'board:notice_write' %}"><button class="btn btn-secondary">글쓰기</button></a>
            </div>
        </div>
    </div>
    <br/>
{% endblock %}
{% block notice_tab %}
    <table class="table table-hover col-lg-12" style="text-align: center;">
        <thead>
        <tr>
            <th class="col-md-1" scope="row">번호</th>
            <th class="col-md-1" scope="row">카테고리</th>
            <th class="col-md-6" scope="row">제목</th>
            <th class="col-md-2" scope="row">등록일</th>
            <th class="col-md-2" scope="row">Handle</th>
        </tr>
        {% if n %}
        {% else %}
            {% if notice_fixed %}
                {% for pin in notice_fixed %}
                    <tr class="table-warning table-hover">
                        <td><i class="fas fa-bullhorn"></i></td>
                        {% if pin.category %}
                            {% if pin.category.name == 'event' %}
                                <td><span class="badge badge-pill badge-warning">{{ pin.category }}</span></td>
                            {% elif pin.category.name == '도서추천' %}
                                <td><span class="badge badge-pill badge-info">{{ pin.category }}</span></td>
                            {% elif pin.category.name == '공지' %}
                                <td><span class="badge badge-pill badge-danger">{{ pin.category }}</span></td>
                            {% else %}
                                <td><span class="badge badge-pill badge-secondary">기타</span></td>
                            {% endif %}
                        {% else %}
                            <td><span class="badge badge-pill badge-secondary">기타</span></td>
                        {% endif %}
                        <td><a href="{{ pin.get_absolute_url }}">{{ pin.title }}</a></td>
                        <td>{{ pin.created_at|date:'Y-m-d' }}</td>
                        <td></td>
                    </tr>
                {% endfor%}
            {% endif %}
        {% endif %}
        </thead>
        <tbody>
        {% for n in notice_list %}
            <tr>
                <th scope="row">{{ n.pk }}</th>
                {% if n.category.name == 'event' %}
                    <td><span class="badge badge-pill badge-warning">{{ n.category }}</span></td>
                {% elif n.category.name == '도서추천' %}
                    <td><span class="badge badge-pill badge-info">{{ n.category }}</span></td>
                {% elif n.category.name == '공지' %}
                    <td><span class="badge badge-pill badge-danger">{{ n.category }}</span></td>
                {% else %}
                    <td><span class="badge badge-pill badge-secondary">기타</span></td>
                {% endif %}
                <td><a href="{{ n.get_absolute_url }}">{{ n.title }}</a></td>
                <td>{{ n.created_at|date:'Y-m-d' }}</td>
                <td>
                    <div class="d-grid gap-2 d-md-block">
                        <a href="/notice/{{ n.pk }}/update/"><button class="btn btn-secondary" type="button">수정</button></a>
                        <a href="/notice/{{ n.pk }}/delete/" onclick="return confirm('정말 {{ n.title }}을(를) 삭제 하시겠습니까?');"><button class="btn btn-danger" type="button">삭제</button></a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{#    페이지네이션#}
{% endblock %}

board/templates/board/notice_write.html
{% extends 'board/base.html' %}
{% load static %}
{% block nav_bar %}
    <div class="container">
        <div class="row">
            <div class="col-auto">
                <a href="{% url 'board:board_list' %}"><button class="btn btn-outline-warning">사보 게시판</button></a>
                <a href="{% url 'board:notice_list' %}"><button class="btn btn-outline-warning">공지사항</button></a>
            </div>
        </div>
    </div>
    <br/>
{% endblock %}
{% block notice_tab %}
<form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-sm">
            {{ form }}
            {{ form.media }}
        </table>
        <div class="text-center">
            <button type="submit" class="btn btn-warning float-none" onclick="return confirm('게시글을 등록 하시겠습니까?');">등록</button>
            <a href="{% url 'board:notice_list' %}" onclick="return confirm('변경된 내용은 저장되지 않습니다.\n그래도 취소하시겠습니까?');">
                <button type="button" class="btn btn-secondary float-none" data-target="">취소</button>
            </a>
        </div>
    </form>
{% endblock %}

board/templates/board/post_detail.html
{% extends 'board/base.html' %}
<!DOCTYPE html>
{% load static %}
{% block nav_bar %}
    <div class="container">
        <div class="row">
            <div class="col-auto">
                <a href="{% url 'board:post_list' %}"><button class="btn btn-outline-warning">사보 게시판</button></a>
                <a href="{% url 'board:notice_list' %}"><button class="btn btn-outline-warning">공지사항</button></a>
            </div>
            <div class="ml-auto">
                <a href="/board/{{ post.pk }}/update">
                    <button class="btn btn-secondary">수정</button>
                </a>
                <a href="/board/{{ post.pk }}/delete" onclick="return confirm('정말 {{ post.title }}을(를) 삭제 하시겠습니까?');">
                    <button class="btn btn-danger">삭제</button>
                </a>
            </div>
        </div>
    </div>
    <br/>
{% endblock %}
{% block sabo_tab %}
    <div class="container-fluid">
        <div class="row" style="text-align: center; background-color: silver;">
            <div class="col-lg-1">No.{{ post.pk }}</div>
            <div class="col-lg-9"><b>{{ post.title }}</b></div>
            <div class="col-lg-2">{{ post.created_at|date:'Y-m-d' }}</div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <p>{{ post.content | safe}}</p>
                {% if post.file_upload %}
                    {% if post.get_file_ext == 'jpg' or post.get_file_ext == 'jpeg' or post.get_file_ext == 'png' or post.get_file_ext == 'jfif' %}
                        <img src="{{ post.file_upload.url }}" alt="{{ post.get_file_name }}">
                        <br/><br/><br/><br/><br/><br/><br/>
                        <span style="background-color: silver;">이미지 다운로드:</span>
                        <a href="{{ post.file_upload.url }}" class="col-lg-auto" style="width:auto; background-color: silver;" role="button" download>
                            <i class="far fa-file-image"></i>{{ post.get_file_name }}
                        </a>
                    {% else %}
                        <br/><br/><br/><br/><br/><br/><br/>
                        <span style="background-color: silver;">첨부파일 다운로드:</span>
                        <a href="{{ post.file_upload.url }}" class="col-lg-auto" style="width:auto; background-color: silver;" role="button" download>
                            {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="far fa-file-excel"></i>
                            {% elif post.get_file_ext == 'txt' %}
                                <i class="far fa-file-alt"></i>
                            {% elif post.get_file_ext == 'pdf' %}
                                <i class="far fa-file-pdf"></i>
                            {% elif post.get_file_ext == 'zip' or post.get_file_ext == '7z' %}
                                <i class="far fa-file-archive"></i>
                            {% else %}
                                <i class="fas fa-file-alt"></i>
                            {% endif %}
                            {{ post.get_file_name }}
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div>
            <div class="text-center">
                <a href="/"><div class="btn btn-light">목록</div></a>
            </div>
        </div>
    </div>
{% endblock %}

board/templates/board/post_set_fix.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h4>고정글 설정</h4>
<table>
    <thead>
    <tr>
        <th>체크박스</th>
        <th>제목</th>
        <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        {% if p %}
        {% else %}
            {% if post_fixed %}
                {% for pin in post_fixed %}
                    <tr class="table-warning table-hover">
                        <td><i class="fas fa-bullhorn"></i></td>
                        <td>{{ pin.title }}</td>
                        <td>{{ pin.created_at|date:'Y-m-d' }}</td>
                        <td></td>
                    </tr>
                {% endfor%}
            {% endif %}
        {% endif %}
    </tr>
    </tbody>
</table>
<div>
    <button>Up</button>
    <button>Down</button>
    <button>설정 저장</button>
</div>
<button>고정글 해제</button>
<table>
    <thead>
    <tr>
        <th>체크박스</th>
        <th>번호</th>
        <th>제목</th>
        <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    {% for p in post_list %}
        <tr>
            <td>o</td>
            <td>{{ p.pk }}</td>
            <td>{{ p.title }}</td>
            <td>{{ p.created_at|date:'Y-m-d' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div>
    << pagination >>
</div>
<div>
    <button>고정글 저장</button>
</div>
<div>
    <button>닫기</button>
</div>
</body>
</html>

board/templates/board/post_top_fix.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h4>고정글 설정</h4>
<table>
    <thead>
    <tr>
        <th>체크박스</th>
        <th>제목</th>
        <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        {% if p %}
        {% else %}
            {% if post_fixed %}
                {% for pin in post_fixed %}
                    <tr class="table-warning table-hover">
                        <td><i class="fas fa-bullhorn"></i></td>
                        <td>{{ pin.title }}</td>
                        <td>{{ pin.created_at|date:'Y-m-d' }}</td>
                        <td></td>
                    </tr>
                {% endfor%}
            {% endif %}
        {% endif %}
    </tr>
    </tbody>
</table>
<div>
    <button>Up</button>
    <button>Down</button>
    <button>설정 저장</button>
</div>
<button>고정글 해제</button>
<table>
    <thead>
    <tr>
        <th>체크박스</th>
        <th>번호</th>
        <th>제목</th>
        <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    {% for p in post_list %}
        <tr>
            <td>o</td>
            <td>{{ p.pk }}</td>
            <td>{{ p.title }}</td>
            <td>{{ p.created_at|date:'Y-m-d' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div>
    << pagination >>
</div>
<div>
    <button>고정글 저장</button>
</div>
<div>
    <button>닫기</button>
</div>
</body>
</html>

board/templates/board/post_write.html
{% extends 'board/base.html' %}
{% load static %}
{% block nav_bar %}
    <div class="container">
        <div class="row">
            <div class="col-auto">
                <a href="{% url 'board:post_list' %}"><button class="btn btn-outline-warning">사보 게시판</button></a>
                <a href="{% url 'board:notice_list' %}"><button class="btn btn-outline-warning">공지사항</button></a>
            </div>
        </div>
    </div>
    <br/>
{% endblock %}
{% block sabo_tab %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-sm">
            {{ form.media }}
            {{ form }}
        </table>
        <div class="text-center">
            {% if 'board:post_write' %}
                <button type="submit" class="btn btn-warning float-none" onclick="return confirm('게시글을 등록 하시겠습니까?');">등록</button>
                {% else %}
                <button type="submit" class="btn btn-warning float-none" onclick="return confirm('게시글을 수정 하시겠습니까?');">수정</button>
            {% endif %}
{#            if url = board/write#}
{#            등록 버튼#}
{#            else#}
{#            수정 버튼#}
{#            endif#}
{#            <button type="submit" class="btn btn-warning float-none" onclick="return confirm('게시글을 등록 하시겠습니까?');">등록</button>#}
            <a href="{% url 'board:post_list' %}" onclick="return confirm('변경된 내용은 저장되지 않습니다.\n그래도 취소하시겠습니까?');">
                <button type="button" class="btn btn-secondary float-none" data-target="">취소</button>
            </a>
        </div>
    </form>
{% endblock %}